version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      target: prod
    image: stockbox---catalog-tree-navigation-frontend
    container_name: stockbox-frontend-prod
    ports:
      - "3000:80"

  backend:
    build: ./backend
    image: stockbox---catalog-tree-navigation-backend
    container_name: stockbox-backend-prod
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000