import {
  Star, Settings, TrendingUp, Search, CheckCircle2, Compass, 
  Camera, Video, Image as ImageIcon, Images, Microscope, Beaker, FlaskConical, TestTube, Rocket,
  Wrench, Shield, Cloud, Database, Folder, FileText, Share2, Users, AlertTriangle, Bell, Calendar,
  Map, MessageSquare, ClipboardList, Box, Package, Layers, Tag, Link, Lock, Unlock, Upload, Download
} from 'lucide-react';


export const ICONS_HE = [
  { value: "star",         label: "כוכב (דגש/מועדפים)",          component: Star },
  { value: "settings",     label: "הגדרות",                       component: Settings },
  { value: "trendingUp",   label: "מגמה/שיפור",                   component: TrendingUp },
  { value: "search",       label: "חיפוש",                        component: Search },
  { value: "checkCircle2", label: "אישור/בדיקה",                  component: CheckCircle2 },
  { value: "compass",      label: "ניווט/מצפן",                    component: Compass },

  { value: "camera",       label: "מצלמה",                        component: Camera },
  { value: "video",        label: "וידאו/צילום",                  component: Video },
  { value: "image",        label: "תמונה",                        component: ImageIcon },
  { value: "images",       label: "גלריה",                        component: Images },
  { value: "microscope",   label: "מיקרוסקופ",                    component: Microscope },
  { value: "beaker",       label: "כוס מדידה (Beaker)",           component: Beaker },
  { value: "flask",        label: "מבקרון (Flask)",               component: FlaskConical },
  { value: "testTube",     label: "מבחנה (Test Tube)",            component: TestTube },
  { value: "rocket",       label: "טיל/ניסוי",                    component: Rocket },

  { value: "wrench",       label: "כלים/תחזוקה",                  component: Wrench },
  { value: "shield",       label: "אבטחה/מגן",                    component: Shield },
  { value: "cloud",        label: "ענן/סנכרון",                    component: Cloud },
  { value: "database",     label: "מסד נתונים",                   component: Database },
  { value: "folder",       label: "תיקייה",                        component: Folder },
  { value: "fileText",     label: "מסמך/קובץ",                     component: FileText },
  { value: "share2",       label: "שיתוף",                         component: Share2 },
  { value: "users",        label: "משתמשים/צוות",                  component: Users },
  { value: "alertTriangle",label: "אזהרה/שגיאה",                   component: AlertTriangle },
  { value: "bell",         label: "התראה/פעמון",                   component: Bell },
  { value: "calendar",     label: "לוח שנה",                       component: Calendar },
  { value: "map",          label: "מפה",                           component: Map },
  { value: "messageSquare",label: "הודעה/דיון",                    component: MessageSquare },
  { value: "clipboardList",label: "רשימת משימות",                  component: ClipboardList },
  { value: "box",          label: "קופסה/מוצר",                    component: Box },
  { value: "package",      label: "חבילה/משלוח",                   component: Package },
  { value: "layers",       label: "שכבות/יררכיה",                  component: Layers },
  { value: "tag",          label: "תגית/קטגוריה",                   component: Tag },
  { value: "link",         label: "קישור",                         component: Link },
  { value: "lock",         label: "נעילה",                         component: Lock },
  { value: "unlock",       label: "פתיחה/שחרור",                   component: Unlock },
  { value: "upload",       label: "העלאה",                         component: Upload },
  { value: "download",     label: "הורדה",                         component: Download },
];
